version: '3.6'
services:
  maxdb:
    image: icd-liberty/db2
    hostname: "${ENV_DB_HOST_NAME}"
    environment:
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - "DB_PORT=${ENV_DB_PORT}"
      - "DB_HOST_NAME=${ENV_DB_HOST_NAME}"
    networks:
      - backend
    ports:
      - "${ENV_DB_PORT}:${ENV_DB_PORT}"
    volumes:
      - type: volume
        source: maxdb76
        target: /data
      - type: bind
        source: ./backup
        target: /backup
    ulimits:
      nproc: 8192
      nofile: 65535
      fsize: -1
    healthcheck:
      test: ["CMD", "/work/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  icd:
    image: icd-liberty/icd
    environment:
      - MXINTADM_PASSWORD=changeit
      - MAXADMIN_PASSWORD=changeit
      - MAXREG_PASSWORD=changeit
      - "DB_PORT=${ENV_DB_PORT}"
      - "DB_HOST_NAME=${ENV_DB_HOST_NAME}"
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - BASE_LANG=en
      #- ADD_LANGS=de,fr,ja
      - ADMIN_EMAIL_ADDRESS=root@localhost
      - SMTP_SERVER_HOST_NAME=localhost
      - SKIN=iot18
      - UPDATE_APPS_ON_REBOOT=yes
      - KEEP_RUNNING=yes
      - ENABLE_DEMO_DATA=no
    depends_on:
      - maxdb
    networks:
      - backend
    volumes:
      - maximo:/maximo

  maximo-ui:
    image: icd-liberty/maximo-ui
    environment:
      - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
      - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
      - LICENSE=accept
      - "JMS_SERVER_HOST=${ENV_JMS_SERVER_HOST}"
      - "JMS_SERVER_PORT=${ENV_JMS_SERVER_PORT}"
      - WLP_LOGGING_CONSOLE_LOGLEVEL=info
    depends_on:
      - maxdb
      - icd
      - jmsserver
    networks:
      frontend:
        aliases:
          - maximo-ui
      backend:
    volumes:
      - maximo:/maximo

  sportal:
    image: icd-liberty/portal
    environment:
      - LICENSE=accept
      - "SPORTAL_SERVER_HOST=${ENV_SPORTAL_SERVER_HOST}"
    depends_on:
     - maxdb
     - icd
     - jmsserver
    hostname: "${ENV_SPORTAL_SERVER_HOST}"
    networks:
      - frontend

  maximo-cron:
    image: icd-liberty/maximo-cron
    environment:
      - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
      - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
      - LICENSE=accept
      - "JMS_SERVER_HOST=${ENV_JMS_SERVER_HOST}"
      - "JMS_SERVER_PORT=${ENV_JMS_SERVER_PORT}"
    depends_on:
      - maxdb
      - icd
      - jmsserver
    networks:
      frontend:
      backend:
    volumes:
      - maximo:/maximo

  maximo-api:
    image: icd-liberty/maximo-api
    environment:
      - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
      - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
      - LICENSE=accept
      - "JMS_SERVER_HOST=${ENV_JMS_SERVER_HOST}"
      - "JMS_SERVER_PORT=${ENV_JMS_SERVER_PORT}"
    depends_on:
      - maxdb
      - icd
      - jmsserver
    networks:
      frontend:
        aliases:
          - maximo-api
      backend:
    volumes:
      - maximo:/maximo

  # maximo-report:
  #   image: maximo-liberty/maximo-report
  #   environment:
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "JMS_SERVER_HOST=${ENV_JMS_SERVER_HOST}"
  #     - "JMS_SERVER_PORT=${ENV_JMS_SERVER_PORT}"
  #   depends_on:
  #     - maxdb
  #     - maximo
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #         - maximo-report
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  maximo-mea:
    image: icd-liberty/maximo-mea
    environment:
      - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
      - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
      - LICENSE=accept
      - "JMS_SERVER_HOST=${ENV_JMS_SERVER_HOST}"
      - "JMS_SERVER_PORT=${ENV_JMS_SERVER_PORT}"
    depends_on:
      - maxdb
      - icd
      - jmsserver
    networks:
     frontend:
       aliases:
         - maximo-mea
     backend:
    volumes:
      - maximo:/maximo

  # maximo-jmsconsumer:
  #   image: maximo-liberty/maximo-jmsconsumer
  #   environment:
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "JMS_SERVER_HOST=${ENV_JMS_SERVER_HOST}"
  #     - "JMS_SERVER_PORT=${ENV_JMS_SERVER_PORT}"
  #   depends_on:
  #     - maxdb
  #     - maximo
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #         - maximo-jmsconsumer
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  jmsserver:
    image: icd-liberty/jmsserver
    environment:
      - LICENSE=accept
      - "JMS_SERVER_HOST=${ENV_JMS_SERVER_HOST}"
      - "JMS_SERVER_PORT=${ENV_JMS_SERVER_PORT}"
      - "JMS_SERVER_SSL_PORT=${ENV_JMS_SERVER_SSL_PORT}"
    hostname: "${ENV_JMS_SERVER_HOST}"
    ports:
      - "${ENV_JMS_SERVER_PORT}:${ENV_JMS_SERVER_PORT}"
      - "${ENV_JMS_SERVER_SSL_PORT}:${ENV_JMS_SERVER_SSL_PORT}"
    networks:
      - frontend

  frontend-proxy:
    image: icd-liberty/frontend-proxy
    ports:
      - 80:80
      - 88:88
    depends_on:
      - maximo-ui
      - sportal
    networks:
      - frontend

networks:
  frontend:
  backend:
volumes:
  maxdb76:
  # Shared directory for liberty deployment files
  maximo:
